#!/usr/bin/env bash

echo "Starting Lune server"
lune run server.luau > server.log &
LUNE_PID=$!

sleep 1

trap "kill $LUNE_PID 2>/dev/null" EXIT

echo "Starting tunnel"
echo "------------------------------------------------------------"

cloudflared tunnel --protocol http2 --no-autoupdate --edge-ip-version 4 --url http://localhost:8080

echo "------------------------------------------------------------"
echo "Kill $LUNE_PID"
kill $LUNE_PID 2>/dev/null
echo "Goodbye"